language: node_js
node_js:
- '10'
jdk:
- oraclejdk8
dist: trusty
script:
- npm run test
- npm run sonar
- npm run build
cache:
  directories:
  - "$HOME/.sonar/cache"
env:
  matrix:
  - SONAR_HOST_URL=https://sonarcloud.io
  global:
    secure: dXMJ7jLS/vcxOroTHXnLafX5O6bZ0k0EZ/Cc9MMz6GB4gm0v/+OxtF8uS14ESVJd3tdwUHb0zBbNTd5vjlzdGfUd3Ctok9pMrgocswaySdyloBxudcfu2+WHtXQc9XqhP/N45MTjplyEI02MSqjwyk/HELXAiwvtpQCheOGU1riaBm3ihXAI1TGWjHgOnqw8tHhS1jUY4VG9eRvk7ypRnVcoyUDmTvT4yQifymFelgawOqGBpGh2gvYfr8XOk+aOnEHI/QGURdtdl07cahMvwpDCPuRdT68ka3aXxfFt4zVnFd8oqY2iFQGOOGKPawfH+56I+JtbS8RZP03cPlqGDOasdcFfujS7J0FJVvxT/2OK70N+JAkIaWH7Yv+Qj0iguo3yNs44LQxWYp4gv4DXdS1LNMqpaDmQsAsc8CaLK1+HnyrRf5yaB0OY44WdmmlFkVe988t0mQfTi6XmPfYa7ZJP7JR69DlLqS7d+u1+xSXlwlpqqFZaDg0ybOA4twfSznLxJJa+AjwzJxBaboHoLqJySuGOKTU7E/u6NyFYel1ZIFC8BdXnd9OyoDRATy8UYPT6hE+Jop6DkxrZ9m5ffeL6RuW6DLj9LcDxm58j/PJcvs8i847qSIw9Hx5VvX4CBY6zC4ZERlZed2x6FeAx6kufgjb++1nqclyNrHza6Ow=
deploy:
  skip_cleanup: true
  provider: npm
  email: arijusg@gmail.com
  api_key:
    secure: 5uq8l/Jbn1BuLndhrqldpKXTFJ/dzH22rOmlY1+FYlBpfrIZYuWy2YRsrTaiQcMBNr44YPEzU3x/QMqVXWlmusTUj7Evaz3iX7/StbjWsJv2rc//8yGuZmsvpx4ag45WgtJrkZsopwWOvHN8gvVUvomaytvje/R0EEPi8NBiBav5iqKDm4nRXfFw15P73t/2OZIVRAeIqU8HHr9XjvTfa9HC6ppLayEKL1P3fnwN3at4eD7Hmj5yWMpHDHh0uVinjSGsJSPAOukWA1uj5FBplv2OKDyl/MZ+rzd3hbqE6rEBOavqwWEsWqOeksm3tLAAn7Lz6RyCEu+zqlldwawOOKgZku9HZfgKrGFR4RY/lXaN3KrHXAF1cok3Y2zYYsomuFu35ajO6CbqTNxE/VYX5SKvXdUCQLKOo3vcUf7RAxxN67OKFSmxvScGR32zOfoVigp5ahWO2HXzfzyZkkusPIm3CDz8ODj/h1J84dbxLdSYL+1IW/PZb0hZmZmrhqhYtvRtKcQ2zNF9ZGEhKKiXjSHvro+LYWVBwl53qWK0nH+Zz9jigaKnYV3mH0JCPvOMNu3v+ryp06Fq9bjBSkcc/AfKaBd+3hyACPUX2oBSYvd/1mUeSFT23lBBBHb5G899zbC5MVub0cFNggDNKcX6xf5gd0t7cixXdnXCmIVOLWs=
  on:
    tags: true
    repo: arijusg/bogus-api
