language: node_js
node_js:
- '6'
jdk:
- oraclejdk8
dist: trusty
script:
- npm run test
- npm run sonar
cache:
  directories:
  - "$HOME/.sonar/cache"
env:
  matrix:
  - SONAR_HOST_URL=https://sonarcloud.io
  global:
    secure: dXMJ7jLS/vcxOroTHXnLafX5O6bZ0k0EZ/Cc9MMz6GB4gm0v/+OxtF8uS14ESVJd3tdwUHb0zBbNTd5vjlzdGfUd3Ctok9pMrgocswaySdyloBxudcfu2+WHtXQc9XqhP/N45MTjplyEI02MSqjwyk/HELXAiwvtpQCheOGU1riaBm3ihXAI1TGWjHgOnqw8tHhS1jUY4VG9eRvk7ypRnVcoyUDmTvT4yQifymFelgawOqGBpGh2gvYfr8XOk+aOnEHI/QGURdtdl07cahMvwpDCPuRdT68ka3aXxfFt4zVnFd8oqY2iFQGOOGKPawfH+56I+JtbS8RZP03cPlqGDOasdcFfujS7J0FJVvxT/2OK70N+JAkIaWH7Yv+Qj0iguo3yNs44LQxWYp4gv4DXdS1LNMqpaDmQsAsc8CaLK1+HnyrRf5yaB0OY44WdmmlFkVe988t0mQfTi6XmPfYa7ZJP7JR69DlLqS7d+u1+xSXlwlpqqFZaDg0ybOA4twfSznLxJJa+AjwzJxBaboHoLqJySuGOKTU7E/u6NyFYel1ZIFC8BdXnd9OyoDRATy8UYPT6hE+Jop6DkxrZ9m5ffeL6RuW6DLj9LcDxm58j/PJcvs8i847qSIw9Hx5VvX4CBY6zC4ZERlZed2x6FeAx6kufgjb++1nqclyNrHza6Ow=
