language: node_js
node_js:
- '6'
jdk:
- oraclejdk8
dist: trusty
script:
- npm i -g typescript
- npm run test
- npm run sonar
- npm run build
cache:
  directories:
  - "$HOME/.sonar/cache"
env:
  matrix:
  - SONAR_HOST_URL=https://sonarcloud.io
  global:
    secure: dXMJ7jLS/vcxOroTHXnLafX5O6bZ0k0EZ/Cc9MMz6GB4gm0v/+OxtF8uS14ESVJd3tdwUHb0zBbNTd5vjlzdGfUd3Ctok9pMrgocswaySdyloBxudcfu2+WHtXQc9XqhP/N45MTjplyEI02MSqjwyk/HELXAiwvtpQCheOGU1riaBm3ihXAI1TGWjHgOnqw8tHhS1jUY4VG9eRvk7ypRnVcoyUDmTvT4yQifymFelgawOqGBpGh2gvYfr8XOk+aOnEHI/QGURdtdl07cahMvwpDCPuRdT68ka3aXxfFt4zVnFd8oqY2iFQGOOGKPawfH+56I+JtbS8RZP03cPlqGDOasdcFfujS7J0FJVvxT/2OK70N+JAkIaWH7Yv+Qj0iguo3yNs44LQxWYp4gv4DXdS1LNMqpaDmQsAsc8CaLK1+HnyrRf5yaB0OY44WdmmlFkVe988t0mQfTi6XmPfYa7ZJP7JR69DlLqS7d+u1+xSXlwlpqqFZaDg0ybOA4twfSznLxJJa+AjwzJxBaboHoLqJySuGOKTU7E/u6NyFYel1ZIFC8BdXnd9OyoDRATy8UYPT6hE+Jop6DkxrZ9m5ffeL6RuW6DLj9LcDxm58j/PJcvs8i847qSIw9Hx5VvX4CBY6zC4ZERlZed2x6FeAx6kufgjb++1nqclyNrHza6Ow=
deploy:
  provider: npm
  email: arijusg@gmail.com
  api_key:
    secure: lNipOQqB0wrG3xsOzvf6f/2VLuV4JBUqA7js+xiHloMLIKpHTrK6SZzyCwyl5TR9YROvTrwgUsZj3qJNq4ybx8EISVZRhXduUPgYse+gUmZgzbgQlGzOToILMEBz4igENSG1e9HO0OXEJgQadEsCg5YALdJ8eGWG4ejcNox6ANVz8theMf81vbWIZFlxU7lyEvEYKbhZKvjglVScPsoZfVR8AFR5nhUVMdSOsW9DwT/lrdEDY0VWCU+v1W1ZoGNlmdYF2Iqwk3s0LHR9C00625ChzcN+PYR+gx9HYpjTgnjkMJmmr2v3qnFHpjHfGV0IxHGrRIlPT3w+FnfQEZtSTDkSDhS9WZarfKHBRJFiZylGl97c1g8o5XCiZr+Mr6r6+uTJk6KMejYD/maZWIhbn+EvPpYYo9VKDN2QW3iZfk09AhOPxbI7lQJIPSaPr+D8xJfuY2+070yVvcDl3Yv2NMxXG5bEw7seSxbzubdmZbc2TVyLVublml84txi7OQJ0sEYh3ung1SmjPDuxBbkEyqEYShXEW7VKSH16Dn/eFjeKHS0AadGyEJjMkQhjQl9DgCRB1vSWTKmL/TXm7EG+X41eqFHA/q0aSEyubxZGrw8rRZP++goEI3MyQSKlTLSFi+Q7LUvDB8iNLKcabOp9VOgG/+dgC8LmopUozRd71Mg=
  on:
    tags: true
    repo: arijusg/bogus-api
